### ISSUE TITLE
Prepare batch send tokens smart contracts for liquid, prepaid, stake topups and new stakings

### ISSUE THREAD

**Issue by zemse** [KMPARDS/esn-contracts#119]

**Comment by zemse** [comment]
As discussed with boss today, this will be done by @maheshrapelli141. 

Last year, I'd worked on a simple UI for bhakti mam to send Liqiud, TSGAP prepaid, and staking rewards using excel file.
https://github.com/KMPARDS/send-eraswaps

To make the process quick and efficient, batch send tokens smart contracts should be used.

**Comment by zemse** [comment]
[Batch Send Contract](https://github.com/KMPARDS/esn-contracts/blob/60158e2bf6479b3c714fbe355170e3b37918d84a/contracts/ESN/BatchSendTokens/BatchSendTokens.sol) is available that helps to batch transactions of ERC20 and Native. 

Since incentive is given to the account that stakes, I don't think this contract can do that. There's an alternative way, first prepaid can to be sent to user, then they can stake so that the incentive is distributed.

cc: @TarunBaur @maheshrapelli141

**Comment by zemse** [comment]
Closing since the contract looks complete.

**Comment by TarunBaur** [comment]
Soham  call me on this point..
